name: AppShell
options:
  minimumXcodeGenVersion: 2.44.0
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.AppShell
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: NO
    ENABLE_USER_SCRIPT_SANDBOXING: NO
configs:
  Debug: debug
  Release: release
packages:
  NativeBridgeCore:
    path: ../NativeBridgeCore
  NewRelic:
    url: https://github.com/newrelic/newrelic-ios-agent-spm
    from: 7.5.4
targets:
  AppShell:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
        excludes:
          - AppShell.xcodeproj
          - project.yml
    dependencies:
      - package: NativeBridgeCore
        product: NativeBridgeCore
      - package: NewRelic
        product: NewRelic
    configFiles:
      Debug: Config/Debug.xcconfig
      Release: Config/Release.xcconfig
    settings:
      configs:
        Debug:
          INFOPLIST_FILE: Info.Debug.plist
        Release:
          INFOPLIST_FILE: Info.Release.plist
    postBuildScripts:
      - name: New Relic dSYM Upload
        shell: /bin/sh
        script: |
          ARTIFACT_DIR="${BUILD_DIR%Build/*}"
          SCRIPT=$(/usr/bin/find "${SRCROOT}" "${ARTIFACT_DIR}" -type f -name run-symbol-tool | head -n 1)
          if [ -n "${SCRIPT}" ] && [ -n "${NEW_RELIC_APP_TOKEN}" ]; then
            /bin/sh "${SCRIPT}" "${NEW_RELIC_APP_TOKEN}"
          else
            echo "New Relic dSYM upload skipped (script or token not found)"
          fi
schemes:
  AppShell:
    build:
      targets:
        AppShell: all
    run:
      config: Debug
      environmentVariables:
        OS_ACTIVITY_MODE: disable
    archive:
      config: Release
